import { Mona_Sans } from 'next/font/google';
import { SpeedInsights } from '@vercel/speed-insights/next';
import type { Metadata } from 'next';
import Footer from './components/footer';
import Navbar from './components/navbar';
import './globals.css';

const monaSans = Mona_Sans({
  variable: '--mona-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'monancial',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`
          ${monaSans.variable} antialiased
          font-[family-name:--mono-sans] font-semibold text-[--foreground] bg-[--background]
        `}
      >
        <Navbar />
        {children}
        <Footer />
        <SpeedInsights />
      </body>
    </html>
  );
}
